lib/auction_web/router.ex
defmodule AuctionWeb.Router do
  use AuctionWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {AuctionWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug AuctionWeb.Plugs.Authenticator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AuctionWeb do
    pipe_through :browser

    get "/", ItemController, :index

    resources "/items", ItemController, only: [:index, :show, :new, :create, :edit, :update] do
      resources "/bids", BidController, only: [:create]
    end

    resources "/users", UserController, only: [:show, :new, :create]
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  scope "/api", AuctionWeb.Api do
    pipe_through :api

    resources "/items", ItemController, only: [:index, :show]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: AuctionWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/auction/core/item.ex
defmodule Auction.Core.Item do
  @moduledoc """
    Represents the data for the different things to be auctioned.
  """

  use Ecto.Schema
  import Ecto.Changeset

  schema "items" do
    field :title, :string
    field :description, :string
    field :ends_at, :utc_datetime
    has_many :bids, Auction.Core.Bid
    timestamps()
  end

  def changeset(item, params \\ %{}) do
    item
    |> cast(params, [:title, :description, :ends_at])
    |> validate_required(:title)
    |> validate_length(:title, min: 3)
    |> validate_length(:description, max: 200)
    |> validate_change(:ends_at, &validate/2)
  end

  defp validate(:ends_at, ends_at_date) do
    case DateTime.compare(ends_at_date, DateTime.utc_now()) do
      :lt -> [ends_at: "can't be in the past"]
      _ -> []
    end
  end
end

lib/auction_web/controllers/api/item_controller.ex
defmodule AuctionWeb.Api.ItemController do
  use AuctionWeb, :controller

  def index(conn, _params) do
    items = Auction.list_items()
    render(conn, "index.json", items: items)
  end

  def show(conn, %{"id" => id}) do
    item = Auction.get_item_with_bids(id)
    render(conn, "show.json", item: item)
  end
end

lib/auction_web/controllers/item_controller.ex
defmodule AuctionWeb.ItemController do
  use AuctionWeb, :controller

  def index(conn, _params) do
    items = Auction.list_items()
    render(conn, "index.html", items: items)
  end

  def show(conn, %{"id" => id}) do
    item = Auction.get_item_with_bids(id)
    bid = Auction.new_bid()
    render(conn, "show.html", item: item, bid: bid)
  end

  def new(conn, _params) do
    item = Auction.new_item()
    render(conn, "new.html", item: item)
  end

  def create(conn, %{"item" => item_params}) do
    case Auction.insert_item(item_params) do
      {:ok, item} -> redirect(conn, to: Routes.item_path(conn, :show, item))
      {:error, item} -> render(conn, "new.html", item: item)
    end
  end

  def update(conn, %{"id" => id, "item" => item_params}) do
    item = Auction.get_item(id)

    case Auction.update_item(item, item_params) do
      {:ok, item} -> redirect(conn, to: Routes.item_path(conn, :show, item))
      {:error, item} -> render(conn, "edit.html", item: item)
    end
  end

  def edit(conn, %{"id" => id}) do
    item = Auction.edit_item(id)
    render(conn, "edit.html", item: item)
  end
end

lib/auction_web/views/item_view.ex
defmodule AuctionWeb.ItemView do
  use AuctionWeb, :view
end

lib/auction_web/templates/item/edit.html.eex
<h1>Edit <%= @item.data.title %></h1>

<%= render("form.html", item: @item, action: Routes.item_path(@conn, :update, @item.data)) %>

lib/auction_web/templates/item/form.html.eex
<%= form_for @item, @action, fn f -> %>
    <%= if @item.action do %>
        <div class="alert alert-danger">
            Unfortunately, there are errors in your
            submission. Please correct them below.
        </div>
    <% end %>

    <%= label f, :title %>
    <%= text_input f, :title %>
    <%= error_tag f, :title %>

    <%= label f, :description %>
    <%= textarea f, :description %>
    <%= error_tag f, :description %>

    <%= label f, :ends_at, "Auction ends at" %>
    <%= datetime_select f, :ends_at %>
    <%= error_tag f, :ends_at %>

    <div>
        <%= submit "Submit" %>
    </div>
<% end %>

lib/auction_web/templates/item/index.html.eex
<ul>
    <%= for item <- @items do %>
    <li>
        <strong><%= link(item.title, to: Routes.item_path(@conn, :show, item)) %></strong>: <%= item.description %>
    </li>
    <% end %>
</ul>

lib/auction_web/templates/item/new.html.eex
<h1>New Item</h1>

<%= render("form.html", item: @item, action: Routes.item_path(@conn, :create)) %>

lib/auction_web/templates/item/show.html.eex
<h1><%= @item.title %></h1>

<ul>
    <li><strong>Description:</strong> <%= @item.description %></li>
    <li><strong>Auction ends at:</strong> <%= @item.ends_at %></li>
</ul>

<div style="display: flex; flex-direction: row;">
    <div style="flex: 1;">
        <h2>Current bids</h2>
        <div id="bids">
            <%= render_many @item.bids, AuctionWeb.BidView, "bid.html" %>
        </div>
    </div>

    <div style="flex: 1;">
        <%= if @current_user do %>
            <h2>Place your bid!</h2>

            <%= form_for @bid, Routes.item_bid_path(@conn, :create, @item), fn f -> %>
                <%= if @bid.action do %>
                    <div class="alert alert-danger">
                        Unfortunately, there are errors in your
                        submission. Please correct them below.
                    </div>
                <% end %>

                <div class="form-group">
                    <%= label f, :amount, "Bid amount", class: "control-label" %>
                    <%= error_tag f, :amount %>
                    <%= number_input f, :amount, class: "form-control" %>
                </div>

                <%= submit "Submit", class: "btn btn-primary"%>
            <% end %>
        <% end %>
    </div>
</div>